4th module

In [8]:
#filling arrays with numpy
import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8,9,10],ndmin=10)
print(arr)

[[[[[[[[[[ 1  2  3  4  5  6  7  8  9 10]]]]]]]]]]


In [11]:
arr=np.array(([1,2,3,4,5,6,7,8,9,10]))
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
arr=np.ones=(2)
print(arr)

2


In [2]:
import numpy as np
arr=np.ones(10)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [3]:
arr=np.ones((50,50))
print(arr)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [10]:
arr=np.ones((51,51))
print(arr)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [4]:
arr=np.arrange=(10,11)
print(arr)

(10, 11)


In [11]:
arr=np.array(['banana','grapes','apple'])
print(arr)

['banana' 'grapes' 'apple']


In [13]:
arr=np.array([2,3,4,5,6,7,8,9])

sorted_array=array=np.sort(arr)
print(sorted_array)

[2 3 4 5 6 7 8 9]


In [14]:
arr=np.array(['alpa','beta','gama','rays'])

sorted_array=array=np.sort(arr)
print(sorted_array)

['alpa' 'beta' 'gama' 'rays']


In [5]:
import numpy as np

arr = np.ones((4,8,3))
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


access array elements

sorting 2d array

In [15]:
arr=np.array([[6,2,3],[9,5,6]])
print( np.sort(arr) )

[[2 3 6]
 [5 6 9]]


Accessing Array elements

In [4]:
import numpy as np
arr = np.array([1,2,3,5,6])

print(arr[-2:])


[5 6]


In [5]:
import numpy as np
arr = np.array([1,2,3,5,6,7,8])

print(arr[-5:-1])

[3 5 6 7]


In [12]:
arr = np.array([1,2,3,5,6,7,8])

print(arr[-5:4])

[3 5]


In [14]:
arr = np.array([10,20,30,50,60,70,80])

print(arr[0:7])

[10 20 30 50 60 70 80]


In [15]:
arr = np.array([10,20,30,50,60,70,80])

print(arr[3:5])

[50 60]


In [27]:
mat=np.array([[10,20,21,22,25],[30,40,41,42,43]])
print(mat)
print(mat[1,2])

[[10 20 21 22 25]
 [30 40 41 42 43]]
41


3d array

In [41]:
import numpy as np
mat=np.array([  [[21,22,25],[41,42,43]]  ,  [[50,51,52],[60,61,62]]  ])
print(mat)
print("value:",mat[1,1,2])

[[[21 22 25]
  [41 42 43]]

 [[50 51 52]
  [60 61 62]]]
value: 62


In [43]:
arr=np.array([1,2,3,4,5,6])

print(arr[1:6:2])

[2 4 6]


In [50]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[1,1:4])

[6 7 8]


searching in array 

In [51]:
arr=np.array([2,50,40,60,70])

val=np.where(arr==40)
print(val)

(array([2], dtype=int64),)


In [56]:
arr=np.array([1,2,3,4,5,])

val=np.where(arr%3==0)
print(val)

(array([2], dtype=int64),)


searchsorted()

In [57]:
arr=np.array([10,20,50,60])

val=np.searchsorted(arr,8)
val

0

In [59]:
arr=np.array([6,7,9,19])
x=np.searchsorted(arr,8)
print(x)

2


In [60]:
np.searchsorted([1,2,3,4,5],3)

2

In [61]:
np.searchsorted([1,2,3,4,5],3,side='right')

3

In [ ]:
np.searchsorted([1,2,3,4,5],)

In [9]:
import numpy as np
arr=np.array(10,20,50,60)
val=np.searchsorted(arr[-10,40,55])
val

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

reshaping array: reshape()

In [64]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
rs=arr.reshape(4,3)
rs

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [67]:
arr=np.array([[1,2],[3,4]])
print(arr.reshape(-1))                   #converting 2d into 1d

[1 2 3 4]


Filtering array: Filter()

In [9]:
import numpy as np
arr=np.array([41,42,43,44,45])
b=[True,False,False,False,True]
newarr=arr[b]
print(newarr)


[41 45]


In [7]:
arr=np.array([0,1,2,3,4,5,8,13])
result=filter(lambda input:input%2!=0,arr)
print(list(result))

[1, 3, 5, 13]


In [12]:
arr=np.array([0,1,2,3,4,5,8,13])
result=filter(lambda input:input%2==0,arr)
print(list(result))

[0, 2, 4, 8]


Joining array

In [29]:
#CONCATENATE()
a=np.arange(6).reshape(2,3)
print (a) 
b=np.arange(7,13).reshape(2,3)
print (b)
np. concatenate((a,b))

[[0 1 2]
 [3 4 5]]
[[ 7  8  9]
 [10 11 12]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [28]:
a=np.arange(6).reshape(2,3)
print("A:",a)

b=np.arange(5,11).reshape(2,3)
print("B:",b)

c=np.concatenate((a,b))
print("concatenated:",c)

A: [[0 1 2]
 [3 4 5]]
B: [[ 5  6  7]
 [ 8  9 10]]
concatenated: [[ 0  1  2]
 [ 3  4  5]
 [ 5  6  7]
 [ 8  9 10]]


In [30]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [31]:
np.stack((a,b))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [33]:
a=np.arange(6).reshape(2,3)
b=np.arange(5,11).reshape(2,3)

mat=np.concatenate((a,b),axis=1)
print(mat)

[[ 0  1  2  5  6  7]
 [ 3  4  5  8  9 10]]


In [34]:
stack_mat=np.stack((a,b))
stack_mat

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 5,  6,  7],
        [ 8,  9, 10]]])

In [35]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  5,  6,  7],
       [ 3,  4,  5,  8,  9, 10]])

VSTACK()

In [36]:
np.vstack((a,b))



array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [37]:
np.hstack((a,b))

array([[ 0,  1,  2,  5,  6,  7],
       [ 3,  4,  5,  8,  9, 10]])

In [38]:
np.dstack((a,b))

array([[[ 0,  5],
        [ 1,  6],
        [ 2,  7]],

       [[ 3,  8],
        [ 4,  9],
        [ 5, 10]]])

In [60]:
mat= np.dstack((a,b))
mat=(mat[1,1,1])
print(mat)

9


PANDAS

In [69]:
import pandas as pd 
import numpy as np
a=np.array([10,20,30,40,50,60,70,80,90,100])
s=pd.Series(a)
s




0     10
1     20
2     30
3     40
4     50
5     60
6     70
7     80
8     90
9    100
dtype: int32

In [80]:
s=pd.Series(a,index=['a','b','c','d','e','f','g','h','i','j'])
s=['i']

In [77]:
li=[1,2,3,4]

a=pd.Series(li)
a

0    1
1    2
2    3
3    4
dtype: int64

Creating Data Frames

In [2]:
import pandas as pd 

list1=[10,20,30,40,[50,60]]
df=pd.DataFrame(data=list1)
print(df)

          0
0        10
1        20
2        30
3        40
4  [50, 60]


In [10]:
import pandas as pd 

bmi= {"age" :[22,23,21,24,23],"gender":["m","f","m","f","m"],"height":[161,164,166,170,169],"weight":[65,66,68,71,74] }

df=pd.DataFrame(bmi)
print(df)

   age gender  height  weight
0   22      m     161      65
1   23      f     164      66
2   21      m     166      68
3   24      f     170      71
4   23      m     169      74


In [18]:
import pandas as pd 

bmi= {"age" :[22,23,21,24,23],"gender":["m","f","m","f","m"],"height":[161,164,166,170,169],"weight":[65,66,68,71,74] }

df=pd.DataFrame(bmi)
#print(df)

list1=[]
for i in range(1):
     elements=(bmi["height"])
     for j in range(len(elements)):
         print(elements[j])

161
164
166
170
169


In [23]:
import pandas as pd 

bmi= {"age" :[22,23,21,24,23],"gender":["m","f","m","f","m"],"height":[161,164,166,170,169],"weight":[65,66,68,71,74] }

df=pd.DataFrame(bmi)
#print(df)

list1=[]
for i in range(1):
     ht=(bmi["height"])
     wt=(bmi["weight"])
     for j in range(len(ht)):
         #print(ht[j])
         #print(wt[j])
         ans=wt[j]/(ht[j]/100)**2
         print(ans)
def healthstatus(ans):
    if(bmi<18.5):
        print("underweight")
    elif(bmi>=18.5 and bmi<)         

SyntaxError: invalid syntax (1544259989.py, line 20)